chamados:
    resource: "@ChamadosBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#sac:
#    resource: "@ChamadosBundle/Controller/"
#    type:     annotation
#    prefix:   /